// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykznkawcnwqwxuzavmvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlrem5rYXdjbndxd3h1emF2bXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MDIxOTcsImV4cCI6MjA2MTM3ODE5N30.nyE8r4Yho90vhho2VCejzwSLjXuNmODKLFUvbQ-epHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);